name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build --if-present

    - name: Run tests
      if: ${{ steps.check_test.outputs.hasTestScript == 'true' }}
      run: npm test

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'  # Only deploy on main branch
      run: |
        npm install --save-dev gh-pages
        npm run deploy

    - name: Check if "test" script exists
      id: check_test
      run: |
        if grep -q '"test":' package.json; then
          echo "hasTestScript=true" >> $GITHUB_ENV
        else
          echo "hasTestScript=false" >> $GITHUB_ENV
        fi
